// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

type Card struct {
	ID                int64    `json:"id"`
	Name              string   `json:"name"`
	Issuer            string   `json:"issuer"`
	Last4Digits       string   `json:"last4_digits"`
	ExpiryDate        string   `json:"expiry_date"`
	DefaultRewardRate *float64 `json:"default_reward_rate"`
	CardType          string   `json:"card_type"`
}
